export const GET_CHAPTER_LIST = 'GET_CHAPTER_LIST'
export const GET_LESSON_LIST = 'GET_LESSON_LIST'


// 新增

export const ADD_LESSON_LIST = 'ADD_LESSON_LIST'

export const DELETE_CHAPTER = 'DELETE_CHAPTER'
export const DELETE_LESSON = 'DELETE_LESSON'
